### ISSUE TITLE
PixelBuffer Version Issue

### ISSUE THREAD

**Issue by mikexu888** [caprica/vlcj-javafx#26] opened 2019-11-14 03:28 UTC
Dear developer,
The current environment JDK is 1.8 with JavaFX 13. However , when it runs a video, it appears below error info:
PixelBuffer has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Then the program can not play the video. I am looking forward you can solve it ASAP. 
Thank you
Best regards,
Mike

**Comment by caprica** [comment] 2019-11-19 19:00
Exact dupe of #25.

JavaFX 13 requires JDK 11 it seems.

There's nothing that can be fixed here.

**Closed by caprica** 2019-11-19 19:00 UTC
